services:
  # bot:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   environment:
  #     - REDIS_URL=redis://cache:6379
  #   links:
  #     - cache
  cache:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  search:
    image: getmeili/meilisearch:v1.3
    ports:
      - 7700:7700
    volumes:
      - meilisearch-data:/meili_data
    env_file: .env

volumes:
  redis:
  meilisearch-data:
