services:
  # bot:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   environment:
  #     - REDIS_URL=redis://cache:6379
  #   links:
  #     - cache
  cache:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  search:
    image: getmeili/meilisearch:v1.9
    ports:
      - 7700:7700
    volumes:
      - meilisearch-data:/meili_data
    env_file: .env
  database:
    image: postgres:16
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  redis:
  meilisearch-data:
  postgres:
