version: '3.8'

services:
  cache:
    image: redis:alpine
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
  search:
    image: getmeili/meilisearch:v1.10
    volumes:
      - meilisearch-data:/meili_data
    env_file: .env
    ports:
      - "7700:7700"
  database:
    image: postgres:16
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  redis:
  meilisearch-data:
  postgres:
